### ISSUE TITLE
Mod license?

### ISSUE THREAD

**Issue by rmtworks** [LexManos/LegacyJavaFixer#2]
Hi there, I wanted to inquire about whether this mod had a license to go with it? Is it fine to use this mod in public modpacks? Thanks in advance!

**Comment by LexManos** [comment]
The license is DO NOT USE AT ALL.
Update your Forge this is no longer needed.

**Comment by rmtworks** [comment]
OK, it was in Tekkit so I had no idea whether it was needed in modern packs. Thanks for clarifying!

**Comment by LexManos** [comment]
Tekkit doing it wrong, color me surprised -.-
